# Generated by Django 4.2.3 on 2023-07-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_ali', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('uniqueid', models.IntegerField(primary_key=True, serialize=False)),
                ('polling_unit_id', models.IntegerField()),
                ('ward_id', models.IntegerField()),
                ('lga_id', models.IntegerField()),
                ('uniquewardid', models.IntegerField()),
                ('polling_unit_number', models.CharField(max_length=100)),
                ('polling_unit_name', models.CharField(max_length=200)),
                ('polling_unit_description', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('entered_by_user', models.CharField(max_length=100)),
                ('date_entered', models.DateField()),
                ('user_ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.DeleteModel(
            name='BincomModel',
        ),
    ]
