# Generated by Django 4.2.3 on 2023-07-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john_ali', '0002_pollingunit_delete_bincommodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pollingunit',
            table='polling_unit',
        ),
    ]
